language: node_js
node_js:
  - '14'
  - '16'
  - 'node'
cache: npm
notifications:
  email: false
before_install:
  - npm install -g codecov
script:
  - npm run test
  - codecov
branches:
  except:
    - '/^v\d+\.\d+\.\d+$/'
jobs:
  include:
    - stage: deploy
      if: branch == master && !fork
      node_js: '8.17.0' # pre-installed version
      script:
        - npm install -g semantic-release@^15
        - semantic-release
